### ISSUE TITLE
Scaling -  retaining original directories in output would be very useful

### ISSUE THREAD

**Issue by inspiraller** [GaelGirodon/markdown-to-document#7]
Technically this isn't a bug, but 
for the benefit of using this plugin to link markdown files between each other-
it's important for tidy folder organisation when scaling.

# Input: 
```
markdownfiles/
  index.md

  cat1_files/
    c1-1.md
    c1-2.md

  cat2_files/
    c2-1.md
```

# build
mdtodoc markdownfiles/* --dest dist/* --theme github --highlight-style atom-one-dark -l basic",
or
mdtodoc markdownfiles/* --dest dist/ --theme github --highlight-style atom-one-dark -l basic",
or
mdtodoc markdownfiles --dest dist --theme github --highlight-style atom-one-dark -l basic",

**Expected output**
```
/dist/
  index.html

  cat1_files/
    c1-1.html
    c1-2.html

  cat2_files/
    c2-1.html
```

**Actual**

`Error: Invalid source(s) (should be valid md files).

**Comment by inspiraller** [comment]
The best I can do is build:
```
mtdoc markdownfiles/**/*.md --dest dist
```
and
```
mtdoc markdownfiles/*.md --dest dist
```
output
```
index.html
c1-1.html
c1-2.html
c2-1.html

```

**Comment by GaelGirodon** [comment]
You're right, Markdown To Document doesn't handle this case.

But one thing to note for your specific use case: since the main goal of `mdtodoc` is to produce self-contained HTML documents (with styles, scripts, ... embedded in the output document), it is not best suited for cases where you have a hierachy of Markdown files having links between them. In this kind of case, you'd better share assets (styles, scripts, images, ...) and avoid generating self-contained documents (where assets would be duplicated in each HTML file). Maybe a classic static site generator (Hugo, Docusaurus, ...) might better suit your needs.

Putting apart the SSG case, this feature could indeed be useful to generate in a single command multiple self-contained documents while keeping the hierarchy in a custom destination directory. But the behavior could be non-trivial, especially if the user provides multiple source file paths (`src/1.md`, `src2/**/*.md`, ...) → which output file paths should be computed? `dest/src/1.md`, `dest/src2/2.md`, ... or `dest/1.md`, `dest/2.md`? To handle the first case and yours, I could compute the common directory of all file paths and concatenate each relative path with the destination path but that can be tricky and it may not match everyone needs.

I think that it's better in this case to keep a full control on file paths and invoke `mdtodoc` multiple times using `find -exec` or `find`/`xargs` 😉
